### ISSUE TITLE
Revise performance claims?

### ISSUE THREAD

**Issue by shoyer** [firmai/pandapy#1]
This is a cool project!

But as noted in https://news.ycombinator.com/item?id=22144101, it's pretty silly to say you're 10-50x faster than pandas when your evidence for that claim is only on very small datasets (~1000 rows).

Performance on datasets of this size is mostly a matter of invoking as little Python overhead as possible. It would be much more interesting to measure performance on datasets with hundreds of thousands or millions of rows. These still fit into memory, but in my experience are much more representative of actual performance bottlenecks.

**Comment by firmai** [comment]
A bout of synchronicity, I was just watching one of your videos on YouTube! I got in touch with you last week re. PDE discovery in finance. Yes, I fully agree. The entire code base have been developed on Google Colab. I will readjust the readme on Monday to warn against this problem. There might be a way to efficiently switch between the two. Let me know if you believe it could at all be solved (cython, numba); from your description it seems like it is a baked in due to not making use of hash tables and columnar data formats.
